services:
  conferenceattendees.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - ASPNETCORE_URLS=http://*:7293
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
 



  conferenceattendees.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - ASPNETCORE_URLS=http://*:7187
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
